services:
  - type: web
    name: payzen
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
    healthCheckPath: /api/healthcheck
    plan: free
    autoDeploy: true 